"""
ULTRAPLAN - Complex Multi-Step Planning System
Deep planning sessions (up to 30 minutes) offloaded to cloud infrastructure

ULTRAPLAN handles complex planning tasks that require:
- Extended reasoning time
- Multi-phase decomposition
- Milestone tracking
- Session persistence and resumption
- Resource-intensive computation
"""
import json
import uuid
from datetime import datetime
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from loguru import logger
from config import settings


class PlanStatus(str, Enum):
    """Status of a planning session"""
    INITIALIZING = "initializing"
    ANALYZING = "analyzing"
    DECOMPOSING = "decomposing"
    PLANNING = "planning"
    REFINING = "refining"
    VALIDATING = "validating"
    COMPLETED = "completed"
    PAUSED = "paused"
    FAILED = "failed"
    CANCELLED = "cancelled"


class MilestoneStatus(str, Enum):
    """Status of a plan milestone"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    SKIPPED = "skipped"


class PlanComplexity(str, Enum):
    """Complexity levels for planning tasks"""
    SIMPLE = "simple"          # < 5 minutes, single-phase
    MODERATE = "moderate"      # 5-15 minutes, multi-phase
    COMPLEX = "complex"        # 15-30 minutes, deep analysis
    EXTENSIVE = "extensive"    # 30+ minutes, may require checkpointing


@dataclass
class PlanMilestone:
    """A milestone within a plan"""
    id: str
    name: str
    description: str
    phase: int
    status: MilestoneStatus = MilestoneStatus.PENDING
    dependencies: List[str] = field(default_factory=list)
    deliverables: List[str] = field(default_factory=list)
    estimated_duration_seconds: int = 300
    actual_duration_seconds: Optional[int] = None
    output: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


@dataclass
class PlanPhase:
    """A phase of the planning process"""
    id: str
    name: str
    description: str
    phase_number: int
    milestones: List[PlanMilestone] = field(default_factory=list)
    status: PlanStatus = PlanStatus.INITIALIZING
    output: Optional[Dict[str, Any]] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


@dataclass
class UltraPlan:
    """A comprehensive plan generated by ULTRAPLAN"""
    id: str
    title: str
    description: str
    goal: str
    complexity: PlanComplexity
    status: PlanStatus = PlanStatus.INITIALIZING
    phases: List[PlanPhase] = field(default_factory=list)
    context: Dict[str, Any] = field(default_factory=dict)
    constraints: List[str] = field(default_factory=list)
    assumptions: List[str] = field(default_factory=list)
    risks: List[Dict[str, Any]] = field(default_factory=list)
    final_output: Optional[Dict[str, Any]] = None
    total_cost: float = 0.0
    estimated_duration_seconds: int = 0
    actual_duration_seconds: Optional[int] = None
    created_at: datetime = field(default_factory=datetime.now)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    checkpoint_data: Optional[Dict[str, Any]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PlanningSession:
    """An active planning session"""
    session_id: str
    plan: UltraPlan
    current_phase: int = 0
    current_milestone: int = 0
    is_paused: bool = False
    last_checkpoint: Optional[datetime] = None
    error_count: int = 0
    callbacks: Dict[str, Callable] = field(default_factory=dict)


class UltraPlanConfig:
    """Configuration for ULTRAPLAN system"""

    def __init__(self):
        self.max_session_duration_seconds: int = getattr(
            settings, "ultraplan_max_session_duration_seconds", 1800
        )  # 30 minutes max
        self.checkpoint_interval_seconds: int = getattr(
            settings, "ultraplan_checkpoint_interval_seconds", 300
        )  # Checkpoint every 5 minutes
        self.max_retries_per_phase: int = getattr(
            settings, "ultraplan_max_retries_per_phase", 3
        )
        self.enable_cloud_offload: bool = getattr(
            settings, "ultraplan_enable_cloud_offload", True
        )
        self.enable_persistence: bool = getattr(
            settings, "ultraplan_enable_persistence", True
        )
        self.storage_path: Path = Path(
            getattr(
                settings,
                "ultraplan_storage_path",
                Path(settings.data_dir) / "ultraplans",
            )
        )
        self.max_parallel_phases: int = getattr(
            settings, "ultraplan_max_parallel_phases", 2
        )
        self.cost_limit_per_plan: float = getattr(
            settings, "ultraplan_cost_limit_per_plan", 5.0
        )  # USD
        self.quality_threshold: float = getattr(
            settings, "ultraplan_quality_threshold", 0.8
        )


class UltraPlanEngine:
    """
    ULTRAPLAN - Complex Multi-Step Planning Engine

    Handles deep planning sessions with:
    1. Task complexity analysis
    2. Multi-phase decomposition
    3. Milestone tracking
    4. Session persistence and resumption
    5. Cloud offloading for intensive computation
    """

    def __init__(self, config: Optional[UltraPlanConfig] = None):
        self.config = config or UltraPlanConfig()
        self.active_sessions: Dict[str, PlanningSession] = {}
        self._router = None
        self._ensure_storage()

        logger.info("ULTRAPLAN engine initialized")

    def _get_router(self):
        """Lazy-load router"""
        if self._router is None:
            from router import router
            self._router = router
        return self._router

    def _ensure_storage(self):
        """Ensure storage directory exists"""
        self.config.storage_path.mkdir(parents=True, exist_ok=True)

    async def create_plan(
        self,
        goal: str,
        context: Optional[Dict[str, Any]] = None,
        constraints: Optional[List[str]] = None,
        time_limit_seconds: Optional[int] = None
    ) -> UltraPlan:
        """
        Create a comprehensive plan for a complex goal.

        Args:
            goal: The objective to plan for
            context: Additional context and requirements
            constraints: Constraints to consider
            time_limit_seconds: Maximum planning time

        Returns:
            UltraPlan with phases, milestones, and deliverables
        """
        session_id = str(uuid.uuid4())
        logger.info(f"🎯 ULTRAPLAN: Creating plan for: {goal[:100]}...")

        # Analyze complexity
        complexity = await self._analyze_complexity(goal, context)
        estimated_duration = self._estimate_duration(complexity)

        if time_limit_seconds:
            estimated_duration = min(estimated_duration, time_limit_seconds)

        # Create plan structure
        plan = UltraPlan(
            id=str(uuid.uuid4()),
            title=await self._generate_title(goal),
            description=goal,
            goal=goal,
            complexity=complexity,
            context=context or {},
            constraints=constraints or [],
            estimated_duration_seconds=estimated_duration,
        )

        # Create session
        session = PlanningSession(
            session_id=session_id,
            plan=plan
        )
        self.active_sessions[session_id] = session

        try:
            # Phase 1: Deep Analysis
            plan.status = PlanStatus.ANALYZING
            plan.started_at = datetime.now()

            analysis = await self._analyze_goal(goal, context, constraints)
            plan.assumptions = analysis.get("assumptions", [])
            plan.risks = analysis.get("risks", [])

            # Phase 2: Decomposition
            plan.status = PlanStatus.DECOMPOSING
            phases = await self._decompose_into_phases(goal, analysis, complexity)
            plan.phases = phases

            # Phase 3: Detailed Planning
            plan.status = PlanStatus.PLANNING
            await self._plan_phase_details(plan)

            # Phase 4: Refinement
            plan.status = PlanStatus.REFINING
            await self._refine_plan(plan)

            # Phase 5: Validation
            plan.status = PlanStatus.VALIDATING
            validation = await self._validate_plan(plan)

            if validation.get("is_valid", False):
                plan.status = PlanStatus.COMPLETED
                plan.completed_at = datetime.now()
                plan.actual_duration_seconds = int(
                    (plan.completed_at - plan.started_at).total_seconds()
                )
            else:
                logger.warning(f"Plan validation issues: {validation.get('issues', [])}")

            # Generate final output
            plan.final_output = await self._generate_plan_output(plan)

            # Persist plan
            if self.config.enable_persistence:
                await self._save_plan(plan)

            logger.info(
                f"✅ ULTRAPLAN complete: {plan.title} "
                f"({len(plan.phases)} phases, {plan.actual_duration_seconds}s)"
            )

            return plan

        except Exception as e:
            logger.error(f"ULTRAPLAN error: {e}")
            plan.status = PlanStatus.FAILED
            plan.metadata["error"] = str(e)
            raise

        finally:
            # Cleanup session
            if session_id in self.active_sessions:
                del self.active_sessions[session_id]

    async def resume_plan(self, plan_id: str) -> UltraPlan:
        """Resume a paused or checkpointed plan"""
        plan = await self._load_plan(plan_id)
        if not plan:
            raise ValueError(f"Plan not found: {plan_id}")

        if plan.status != PlanStatus.PAUSED:
            raise ValueError(f"Plan is not paused: {plan.status}")

        logger.info(f"Resuming plan: {plan.title}")
        plan.status = PlanStatus.PLANNING

        # Continue from checkpoint
        # ... implementation continues from checkpoint_data

        return plan

    async def pause_plan(self, session_id: str) -> bool:
        """Pause an active planning session"""
        if session_id not in self.active_sessions:
            return False

        session = self.active_sessions[session_id]
        session.is_paused = True
        session.plan.status = PlanStatus.PAUSED
        session.plan.checkpoint_data = await self._create_checkpoint(session)

        if self.config.enable_persistence:
            await self._save_plan(session.plan)

        logger.info(f"Plan paused: {session.plan.title}")
        return True

    async def cancel_plan(self, session_id: str) -> bool:
        """Cancel an active planning session"""
        if session_id not in self.active_sessions:
            return False

        session = self.active_sessions[session_id]
        session.plan.status = PlanStatus.CANCELLED
        session.plan.completed_at = datetime.now()

        del self.active_sessions[session_id]

        logger.info(f"Plan cancelled: {session.plan.title}")
        return True

    def get_session_status(self, session_id: str) -> Optional[Dict[str, Any]]:
        """Get status of an active planning session"""
        if session_id not in self.active_sessions:
            return None

        session = self.active_sessions[session_id]
        return {
            "session_id": session_id,
            "plan_id": session.plan.id,
            "title": session.plan.title,
            "status": session.plan.status.value,
            "current_phase": session.current_phase,
            "total_phases": len(session.plan.phases),
            "is_paused": session.is_paused,
            "elapsed_seconds": (datetime.now() - session.plan.started_at).total_seconds()
            if session.plan.started_at else 0,
        }

    async def _analyze_complexity(
        self,
        goal: str,
        context: Optional[Dict[str, Any]]
    ) -> PlanComplexity:
        """Analyze the complexity of a planning goal"""
        # Use LLM to assess complexity
        prompt = f"""Analyze the complexity of this planning goal.

Goal: {goal}
Context: {json.dumps(context or {}, indent=2)}

Rate the complexity on this scale:
- SIMPLE: Single-phase task, straightforward approach, < 5 minutes
- MODERATE: Multi-phase task, some dependencies, 5-15 minutes
- COMPLEX: Many interdependencies, requires deep analysis, 15-30 minutes
- EXTENSIVE: Highly complex, requires extensive research, 30+ minutes

Respond with ONLY one word: SIMPLE, MODERATE, COMPLEX, or EXTENSIVE"""

        try:
            decision, result = await self._get_router().execute_with_routing(
                task=prompt,
                context={"requires_reasoning": True}
            )

            content = result.get("content", "").strip().upper()
            if "EXTENSIVE" in content:
                return PlanComplexity.EXTENSIVE
            elif "COMPLEX" in content:
                return PlanComplexity.COMPLEX
            elif "MODERATE" in content:
                return PlanComplexity.MODERATE
            else:
                return PlanComplexity.SIMPLE

        except Exception as e:
            logger.warning(f"Complexity analysis failed: {e}")
            return PlanComplexity.MODERATE

    def _estimate_duration(self, complexity: PlanComplexity) -> int:
        """Estimate planning duration based on complexity"""
        durations = {
            PlanComplexity.SIMPLE: 180,      # 3 minutes
            PlanComplexity.MODERATE: 600,    # 10 minutes
            PlanComplexity.COMPLEX: 1200,    # 20 minutes
            PlanComplexity.EXTENSIVE: 1800,  # 30 minutes
        }
        return durations.get(complexity, 600)

    async def _generate_title(self, goal: str) -> str:
        """Generate a concise title for the plan"""
        prompt = f"""Generate a concise title (max 50 characters) for this planning goal:

Goal: {goal}

Respond with ONLY the title, no quotes or explanation."""

        try:
            decision, result = await self._get_router().execute_with_routing(
                task=prompt,
                context={"simple_task": True}
            )
            return result.get("content", goal[:50]).strip()[:50]
        except Exception:
            return goal[:50]

    async def _analyze_goal(
        self,
        goal: str,
        context: Optional[Dict[str, Any]],
        constraints: Optional[List[str]]
    ) -> Dict[str, Any]:
        """Deep analysis of the goal"""
        prompt = f"""Perform a deep analysis of this planning goal.

Goal: {goal}

Context: {json.dumps(context or {}, indent=2)}

Constraints: {json.dumps(constraints or [], indent=2)}

Analyze and provide:
1. Key assumptions that need to be made
2. Potential risks and mitigation strategies
3. Success criteria
4. Resource requirements
5. External dependencies

Respond in JSON format:
{{
    "assumptions": ["assumption 1", "assumption 2"],
    "risks": [
        {{"risk": "description", "impact": "high/medium/low", "mitigation": "strategy"}}
    ],
    "success_criteria": ["criterion 1", "criterion 2"],
    "resources": ["resource 1", "resource 2"],
    "dependencies": ["dependency 1", "dependency 2"]
}}"""

        decision, result = await self._get_router().execute_with_routing(
            task=prompt,
            context={"requires_reasoning": True}
        )

        content = result.get("content", "")
        try:
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                return json.loads(content[start:end])
        except json.JSONDecodeError:
            pass

        return {
            "assumptions": [],
            "risks": [],
            "success_criteria": [],
            "resources": [],
            "dependencies": []
        }

    async def _decompose_into_phases(
        self,
        goal: str,
        analysis: Dict[str, Any],
        complexity: PlanComplexity
    ) -> List[PlanPhase]:
        """Decompose goal into planning phases"""
        # Determine number of phases based on complexity
        phase_counts = {
            PlanComplexity.SIMPLE: 2,
            PlanComplexity.MODERATE: 3,
            PlanComplexity.COMPLEX: 5,
            PlanComplexity.EXTENSIVE: 7,
        }
        target_phases = phase_counts.get(complexity, 3)

        prompt = f"""Decompose this planning goal into {target_phases} sequential phases.

Goal: {goal}

Analysis context:
- Assumptions: {json.dumps(analysis.get("assumptions", []))}
- Risks: {json.dumps(analysis.get("risks", []))}
- Dependencies: {json.dumps(analysis.get("dependencies", []))}

Create {target_phases} phases, each with:
1. Clear name and description
2. 2-4 milestones per phase
3. Dependencies between milestones
4. Expected deliverables

Respond in JSON:
{{
    "phases": [
        {{
            "name": "Phase Name",
            "description": "Phase description",
            "milestones": [
                {{
                    "name": "Milestone name",
                    "description": "What this milestone achieves",
                    "deliverables": ["deliverable 1"],
                    "estimated_duration_seconds": 300,
                    "dependencies": []
                }}
            ]
        }}
    ]
}}"""

        decision, result = await self._get_router().execute_with_routing(
            task=prompt,
            context={"requires_reasoning": True}
        )

        content = result.get("content", "")
        phases = []

        try:
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])

                for i, phase_data in enumerate(data.get("phases", [])):
                    milestones = []
                    for j, m_data in enumerate(phase_data.get("milestones", [])):
                        milestone = PlanMilestone(
                            id=f"m_{i}_{j}",
                            name=m_data.get("name", f"Milestone {j+1}"),
                            description=m_data.get("description", ""),
                            phase=i,
                            deliverables=m_data.get("deliverables", []),
                            estimated_duration_seconds=m_data.get("estimated_duration_seconds", 300),
                            dependencies=m_data.get("dependencies", [])
                        )
                        milestones.append(milestone)

                    phase = PlanPhase(
                        id=f"phase_{i}",
                        name=phase_data.get("name", f"Phase {i+1}"),
                        description=phase_data.get("description", ""),
                        phase_number=i,
                        milestones=milestones
                    )
                    phases.append(phase)

        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse phases: {e}")

        # Ensure at least one phase
        if not phases:
            phases = [PlanPhase(
                id="phase_0",
                name="Main Phase",
                description="Execute the plan",
                phase_number=0,
                milestones=[PlanMilestone(
                    id="m_0_0",
                    name="Main Objective",
                    description=goal,
                    phase=0
                )]
            )]

        return phases

    async def _plan_phase_details(self, plan: UltraPlan):
        """Add detailed planning to each phase"""
        for phase in plan.phases:
            phase.status = PlanStatus.PLANNING
            phase.started_at = datetime.now()

            for milestone in phase.milestones:
                milestone.status = MilestoneStatus.IN_PROGRESS
                milestone.started_at = datetime.now()

                # Generate detailed plan for milestone
                prompt = f"""Create a detailed action plan for this milestone.

Plan Context: {plan.goal}
Phase: {phase.name}
Milestone: {milestone.name}
Description: {milestone.description}
Deliverables: {json.dumps(milestone.deliverables)}

Provide specific, actionable steps to achieve this milestone.
Include any tools, resources, or considerations needed.

Respond in JSON:
{{
    "steps": ["step 1", "step 2"],
    "tools_needed": ["tool 1"],
    "considerations": ["consideration 1"],
    "success_metrics": ["metric 1"]
}}"""

                try:
                    decision, result = await self._get_router().execute_with_routing(
                        task=prompt,
                        context={"requires_reasoning": True}
                    )

                    content = result.get("content", "")
                    start = content.find("{")
                    end = content.rfind("}") + 1

                    if start >= 0 and end > start:
                        milestone.output = json.loads(content[start:end])

                    plan.total_cost += decision.estimated_cost

                except Exception as e:
                    logger.warning(f"Milestone planning error: {e}")
                    milestone.output = {"error": str(e)}

                milestone.status = MilestoneStatus.COMPLETED
                milestone.completed_at = datetime.now()
                milestone.actual_duration_seconds = int(
                    (milestone.completed_at - milestone.started_at).total_seconds()
                )

            phase.status = PlanStatus.COMPLETED
            phase.completed_at = datetime.now()

    async def _refine_plan(self, plan: UltraPlan):
        """Refine and optimize the plan"""
        # Gather all phase outputs for review
        phase_summaries = []
        for phase in plan.phases:
            milestone_outputs = [m.output for m in phase.milestones if m.output]
            phase_summaries.append({
                "phase": phase.name,
                "milestones": [m.name for m in phase.milestones],
                "outputs": milestone_outputs[:2]  # Limit for prompt size
            })

        prompt = f"""Review and refine this plan for quality and completeness.

Goal: {plan.goal}

Current Plan Summary:
{json.dumps(phase_summaries, indent=2)}

Identify:
1. Any gaps or missing steps
2. Potential optimizations
3. Risk areas that need more attention
4. Suggested improvements

Provide refinement suggestions in JSON:
{{
    "gaps": ["gap 1"],
    "optimizations": ["optimization 1"],
    "risk_areas": ["risk 1"],
    "improvements": ["improvement 1"],
    "overall_quality_score": 0.85
}}"""

        try:
            decision, result = await self._get_router().execute_with_routing(
                task=prompt,
                context={"requires_reasoning": True}
            )

            content = result.get("content", "")
            start = content.find("{")
            end = content.rfind("}") + 1

            if start >= 0 and end > start:
                refinements = json.loads(content[start:end])
                plan.metadata["refinements"] = refinements
                plan.total_cost += decision.estimated_cost

        except Exception as e:
            logger.warning(f"Plan refinement error: {e}")

    async def _validate_plan(self, plan: UltraPlan) -> Dict[str, Any]:
        """Validate the plan for completeness and feasibility"""
        validation = {
            "is_valid": True,
            "issues": [],
            "warnings": [],
            "score": 0.0
        }

        # Check for empty phases
        if not plan.phases:
            validation["is_valid"] = False
            validation["issues"].append("No phases defined")

        # Check milestone completeness
        for phase in plan.phases:
            if not phase.milestones:
                validation["warnings"].append(f"Phase '{phase.name}' has no milestones")

            for milestone in phase.milestones:
                if not milestone.deliverables:
                    validation["warnings"].append(
                        f"Milestone '{milestone.name}' has no deliverables"
                    )

        # Check dependencies
        all_milestone_ids = {m.id for p in plan.phases for m in p.milestones}
        for phase in plan.phases:
            for milestone in phase.milestones:
                for dep in milestone.dependencies:
                    if dep not in all_milestone_ids:
                        validation["issues"].append(
                            f"Invalid dependency '{dep}' in milestone '{milestone.name}'"
                        )

        # Calculate validation score
        # Each issue reduces score fully, warnings count partially
        warning_penalty_weight = 0.5
        minimum_validity_score = 0.6
        total_checks = 3 + len(plan.phases) * 2
        passed_checks = total_checks - len(validation["issues"]) - (len(validation["warnings"]) * warning_penalty_weight)
        validation["score"] = max(0, passed_checks / total_checks)

        if validation["score"] < minimum_validity_score:
            validation["is_valid"] = False

        return validation

    async def _generate_plan_output(self, plan: UltraPlan) -> Dict[str, Any]:
        """Generate final plan output summary"""
        return {
            "plan_id": plan.id,
            "title": plan.title,
            "goal": plan.goal,
            "complexity": plan.complexity.value,
            "status": plan.status.value,
            "summary": {
                "total_phases": len(plan.phases),
                "total_milestones": sum(len(p.milestones) for p in plan.phases),
                "estimated_duration_seconds": plan.estimated_duration_seconds,
                "actual_duration_seconds": plan.actual_duration_seconds,
                "total_cost": plan.total_cost,
            },
            "phases": [
                {
                    "name": phase.name,
                    "description": phase.description,
                    "milestones": [
                        {
                            "name": m.name,
                            "description": m.description,
                            "deliverables": m.deliverables,
                            "steps": m.output.get("steps", []) if m.output else []
                        }
                        for m in phase.milestones
                    ]
                }
                for phase in plan.phases
            ],
            "assumptions": plan.assumptions,
            "risks": plan.risks,
            "refinements": plan.metadata.get("refinements", {}),
            "created_at": plan.created_at.isoformat(),
            "completed_at": plan.completed_at.isoformat() if plan.completed_at else None,
        }

    async def _create_checkpoint(self, session: PlanningSession) -> Dict[str, Any]:
        """Create a checkpoint for session resumption"""
        return {
            "checkpoint_time": datetime.now().isoformat(),
            "current_phase": session.current_phase,
            "current_milestone": session.current_milestone,
            "completed_phases": [
                p.id for p in session.plan.phases
                if p.status == PlanStatus.COMPLETED
            ],
            "plan_state": session.plan.status.value,
        }

    async def _save_plan(self, plan: UltraPlan):
        """Save plan to persistent storage"""
        filepath = self.config.storage_path / f"{plan.id}.json"

        plan_data = {
            "id": plan.id,
            "title": plan.title,
            "goal": plan.goal,
            "complexity": plan.complexity.value,
            "status": plan.status.value,
            "final_output": plan.final_output,
            "total_cost": plan.total_cost,
            "created_at": plan.created_at.isoformat(),
            "completed_at": plan.completed_at.isoformat() if plan.completed_at else None,
            "checkpoint_data": plan.checkpoint_data,
            "metadata": plan.metadata,
        }

        filepath.write_text(json.dumps(plan_data, indent=2))
        logger.info(f"Plan saved: {filepath}")

    async def _load_plan(self, plan_id: str) -> Optional[UltraPlan]:
        """Load plan from persistent storage"""
        filepath = self.config.storage_path / f"{plan_id}.json"

        if not filepath.exists():
            return None

        try:
            data = json.loads(filepath.read_text())
            # Reconstruct plan from saved data
            # (simplified - full implementation would rebuild all objects)
            plan = UltraPlan(
                id=data["id"],
                title=data["title"],
                description=data["goal"],
                goal=data["goal"],
                complexity=PlanComplexity(data["complexity"]),
                status=PlanStatus(data["status"]),
                final_output=data.get("final_output"),
                total_cost=data.get("total_cost", 0),
                checkpoint_data=data.get("checkpoint_data"),
                metadata=data.get("metadata", {}),
            )
            return plan
        except Exception as e:
            logger.error(f"Failed to load plan: {e}")
            return None


# Global ULTRAPLAN engine instance
ultraplan = UltraPlanEngine()


async def create_ultraplan(
    goal: str,
    context: Optional[Dict[str, Any]] = None,
    constraints: Optional[List[str]] = None,
    time_limit_seconds: Optional[int] = None
) -> UltraPlan:
    """Convenience function to create an ULTRAPLAN"""
    return await ultraplan.create_plan(goal, context, constraints, time_limit_seconds)
