"""Synthesis Engine — Multi-document distillation and e-book generation.

Takes high-density knowledge (folders, tags, fragments) and 
synthesizes it into structured business intelligence reports.
"""
import os
import time
from typing import List, Dict, Optional

class SynthesisEngine:
    """Synthesizes raw data into structured intelligence."""
    
    def synthesize(self, tag: str, fragments: List[Dict]) -> Dict:
        """Create a 'Knowledge Synthesis' report from a collection of fragments."""
        if not fragments:
            return {"status": "error", "message": "No fragments to synthesize"}
            
        report_id = f"synth-{tag}-{int(time.time())}"
        report_title = f"Executive Briefing: {tag.capitalize()} & Market Dynamics"
        
        # Structure the synthesis
        synthesis = [
            f"# {report_title}",
            f"Generated by Aether OS on {time.strftime('%Y-%m-%d')}",
            "",
            "## 1. Executive Summary",
            f"This report synthesizes {len(fragments)} data nodes regarding {tag}.",
            "",
            "## 2. Key Insights & Trends",
        ]
        
        # Simple extraction of titles/snippets
        for i, f in enumerate(fragments[:5]):
            synthesis.append(f"### Insight {i+1}: {f.get('source_title', 'Untitled Fragment')}")
            synthesis.append(f.get('chunk_text', '')[:400] + "...")
            synthesis.append("")
            
        synthesis.append("## 3. Recommended Strategic Actions")
        synthesis.append("- Leverage these insights for content creation")
        synthesis.append("- Update technical documentation in Knowledge Bank")
        synthesis.append("- Scout for market opportunities in Intel Hub")
        synthesis.append("")
        synthesis.append("## 4. Deterministic Audit Trail (Hallucination Proof)")
        synthesis.append("The following source nodes were used for this synthesis. No external unverified data was injected.")
        for f in fragments[:10]:
            synthesis.append(f"- **{f.get('source_title', 'Untitled')}** (Node: {f.get('id', 'unknown')})")
        
        full_text = "\n".join(synthesis)
        
        # Save to knowledge refs
        os.makedirs("knowledge_bank/synthesis", exist_ok=True)
        path = f"knowledge_bank/synthesis/{report_id}.md"
        with open(path, "w") as f:
            f.write(full_text)
            
        return {
            "id": report_id,
            "title": report_title,
            "path": path,
            "summary": f"Synthesized {len(fragments)} fragments into a structured briefing.",
            "timestamp": time.time()
        }

_SYNTHESIS: Optional[SynthesisEngine] = None

def get_synthesis_engine() -> SynthesisEngine:
    global _SYNTHESIS
    if _SYNTHESIS is None: _SYNTHESIS = SynthesisEngine()
    return _SYNTHESIS
