"""GitHub Issue Queue Dispatcher — creates, tracks, and resolves HITL issues."""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import requests

from coo.state import DecisionCard, TrafficLightZone

logger = logging.getLogger(__name__)


class GitHubCredentialsError(Exception):
    """Raised when GitHub token is missing or invalid."""
    pass


@dataclass
class GitHubIssuePayload:
    title: str
    body: str
    labels: List[str] = field(default_factory=list)


@dataclass
class GitHubIssue:
    issue_number: int
    title: str
    is_closed: bool
    labels: List[str] = field(default_factory=list)
    url: str = ""


def build_issue_payload(card: DecisionCard) -> GitHubIssuePayload:
    """Build a structured GitHub Issue payload from a DecisionCard."""
    zone_tag = card.zone.value.upper()
    title = f"[{zone_tag}] {card.summary}"

    body = f"""## [{zone_tag}] {card.summary}

### Product
- **Product:** {card.product_id}
- **Event ID:** {card.event_id}
- **Zone:** {card.zone.value}

### 🚨 Diagnostic Report
{card.diagnosis}

### 🔍 Analysis
The COO Brain has analyzed the telemetry and identified the root cause.
This event requires human review before any autonomous action is taken.

### 🛠️ Proposed Solution
{card.proposed_fix}

{f'### 📝 Code Change (PR #{card.github_pr_number})\n{card.code_change}\n' if card.code_change else ''}

### 📥 Instructions to Proceed
1. To **APPROVE** and execute, simply **CLOSE this issue**.
2. To **REJECT** or revise, comment on this issue.
3. For **RED** zone events: do not auto-merge — escalate to principal immediately.

---
*Generated by Deterministic Brain COO • Event ID: {card.event_id}*
"""

    labels = [
        "coo-brain",
        card.zone.value,
        card.zone.value + "-zone",
        card.product_id,
    ]

    return GitHubIssuePayload(title=title, body=body, labels=labels)


def build_pr_payload(card: DecisionCard, pr_url: str) -> GitHubIssuePayload:
    """Build a GitHub Issue payload that references an existing PR."""
    zone_tag = card.zone.value.upper()
    title = f"[{zone_tag}] PR Review: {card.summary}"
    pr_num = card.github_pr_number or 0

    body = f"""## [{zone_tag}] PR Review Required

### Product
- **Product:** {card.product_id}
- **PR:** #{pr_num} ({pr_url})
- **Zone:** {card.zone.value}

### 🚨 Diagnostic Report
{card.diagnosis}

### 🛠️ Proposed Solution
{card.proposed_fix}

### 📥 Instructions to Proceed
1. Review PR #{pr_num} at {pr_url}
2. To **APPROVE** and merge, **CLOSE this issue**.
3. To **REJECT**, comment with requested changes.

---
*Generated by Deterministic Brain COO • Event ID: {card.event_id}*
"""

    labels = ["coo-brain", card.zone.value, "pr-review", card.product_id]

    return GitHubIssuePayload(title=title, body=body, labels=labels)


class GitHubQueue:
    """Manages GitHub Issues as the Human-in-the-Loop decision queue."""

    def __init__(self, token: str = "", owner: str = "", repo: str = ""):
        self._token = token
        self._owner = owner
        self._repo = repo
        self._base_url = f"https://api.github.com/repos/{owner}/{repo}"
        self._headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        } if token else {}

    def _post(self, url: str, data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """POST with error handling — returns None on failure."""
        if not self._token:
            logger.error("GitHubQueue: no token configured")
            return None
        try:
            resp = requests.post(url, headers=self._headers, json=data, timeout=15)
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.RequestException as e:
            logger.error("GitHubQueue POST failed: %s", e)
            return None

    def _get(self, url: str) -> Optional[Dict[str, Any]]:
        """GET with error handling — returns None on failure."""
        if not self._token:
            logger.error("GitHubQueue: no token configured")
            return None
        try:
            resp = requests.get(url, headers=self._headers, timeout=15)
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.RequestException as e:
            logger.error("GitHubQueue GET failed: %s", e)
            return None

    def open_issue(self, card: DecisionCard) -> Optional[DecisionCard]:
        """Create a GitHub Issue for a DecisionCard. Returns updated card with issue number."""
        payload = build_issue_payload(card)
        url = f"{self._base_url}/issues"
        data = {
            "title": payload.title,
            "body": payload.body,
            "labels": payload.labels,
        }

        result = self._post(url, data)
        if result is None:
            return None

        card.github_issue_number = result.get("number")
        logger.info(
            "GitHubQueue: opened issue #%d for event %s (%s)",
            card.github_issue_number,
            card.event_id,
            card.zone.value,
        )
        return card

    def get_issue(self, issue_number: int) -> Optional[GitHubIssue]:
        """Fetch a GitHub Issue by number."""
        url = f"{self._base_url}/issues/{issue_number}"
        result = self._get(url)
        if result is None:
            return None

        labels = [l["name"] for l in result.get("labels", [])]
        return GitHubIssue(
            issue_number=result.get("number", issue_number),
            title=result.get("title", ""),
            is_closed=result.get("state") == "closed",
            labels=labels,
            url=result.get("html_url", ""),
        )

    def close_issue(self, issue_number: int, outcome: str = "approved") -> bool:
        """Close an issue with a resolution comment."""
        url = f"{self._base_url}/issues/{issue_number}"
        body = f"COO Brain: Issue closed with outcome '{outcome}'. Marking event as resolved."
        data = {"state": "closed", "body": body}

        result = self._post(url, data)
        if result is None:
            return False

        logger.info("GitHubQueue: closed issue #%d with outcome '%s'", issue_number, outcome)
        return True

    def list_open_issues(self, labels: Optional[List[str]] = None) -> List[GitHubIssue]:
        """List open issues, optionally filtered by labels."""
        url = f"{self._base_url}/issues"
        params = {"state": "open", "per_page": 50}
        if labels:
            params["labels"] = ",".join(labels)

        if not self._token:
            return []

        try:
            resp = requests.get(url, headers=self._headers, params=params, timeout=15)
            resp.raise_for_status()
            issues = resp.json()
        except requests.exceptions.RequestException as e:
            logger.error("GitHubQueue list_open_issues failed: %s", e)
            return []

        return [
            GitHubIssue(
                issue_number=i.get("number", 0),
                title=i.get("title", ""),
                is_closed=i.get("state") == "closed",
                labels=[l["name"] for l in i.get("labels", [])],
                url=i.get("html_url", ""),
            )
            for i in issues
        ]


_queue_instance: Optional[GitHubQueue] = None


def get_queue(
    token: str = "",
    owner: str = "ncsound919",
    repo: str = "claw-protect",
) -> GitHubQueue:
    """Get or create the singleton GitHubQueue."""
    global _queue_instance
    if _queue_instance is None:
        _queue_instance = GitHubQueue(token=token, owner=owner, repo=repo)
    return _queue_instance